codecov:
  notify:
    require_ci_to_pass: yes

ignore:
  - **/*.stories.tsx

coverage:
  precision: 5
  round: down

  status:
    project:
      default:
        target: auto
        threshold: 0.1
    patch:
      default:
        target: 50%
    changes: no
